### PR TITLE
Fix alignments

### PR DESCRIPTION
**Pull request by amoludage**
I have fixed the alignment for all the files.

### CODE REVIEW

**Comment by quentint** [comment]
Sorry but this is not an improvement, code formatting is only a user's preference.

**Comment by amoludage** [comment]
@quentint I think it is good to have better formatting of code, It's  also useful for easily understanding the code.
Currently code formatting is very bad.

Thanks :blush:

**Comment by quentint** [comment]
"Very bad" probably means you don't like tabulation indentation, but again, that's a personal preference.

**Comment by amoludage** [comment]
Ok, leave this as it is.

Thanks.

**Pull request closed without merging**
